/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-2",
  aws_appsync_graphqlEndpoint:
    "https://unfndeb6lff2pmtuecludkny7i.appsync-api.us-east-2.amazonaws.com/graphql",
  aws_appsync_region: "us-east-2",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-zy3eupu43vfxnmhxshrrpek4su",
  aws_cloudfront_domain: "d3qfzh71og45l0.cloudfront.net",
};

export default awsmobile;
